using System.Collections.Generic;

namespace HKX2
{
    /// <summary>
    /// Havok classes whose generated Read/Write bodies still carry padding
    /// hardcoded to Skyrim SE's 8-byte pointer, so they cannot be read from or
    /// written to a 32-bit (Skyrim LE) packfile.
    ///
    /// They fall into three groups: hkp* physics/ragdoll classes whose layout
    /// the generator cannot derive (multiple inheritance and vtable-only
    /// interfaces), Havok type-metadata and runtime-only classes that never
    /// appear in a serialised file, and hkbGeneratorSyncInfo, whose SE body has
    /// a pre-existing 8-byte over-read.
    ///
    /// None of them occur in behaviour, character, project, skeleton or
    /// animation files.  Generated by tools/hkx-layout-gen/relayout.py.
    /// </summary>
    public static class PointerSizeSupport
    {
        public static readonly IReadOnlySet<string> SkyrimSeOnlyClasses = new HashSet<string>
        {
            "hkClass",
            "hkClassEnum",
            "hkClassMember",
            "hkCustomAttributes",
            "hkCustomAttributesAttribute",
            "hkPackfileSectionHeader",
            "hkaFootstepAnalysisInfo",
            "hkbCharacter",
            "hkbGeneratorSyncInfo",
            "hkpCollidableCollidableFilter",
            "hkpCompressedMeshShape",
            "hkpConstraintCollisionFilter",
            "hkpListShape",
            "hkpRayCollidableFilter",
            "hkpRayShapeCollectionFilter",
            "hkpShapeCollectionFilter",
            "hkpShapeContainer",
            "hkpSingleShapeContainer",
            "hkpWorld",
        };

        /// <summary>True if <paramref name="className"/> can be read from or
        /// written to a packfile with the given pointer size.</summary>
        public static bool Supports(string className, int pointerSize)
            => pointerSize == 8 || !SkyrimSeOnlyClasses.Contains(className);
    }
}
